package cards

import "perfectOddsBot/models"

func registerCommonCards(deck *[]models.Card) {
	// commonCards := []models.Card{
	// 	{
	// 		ID:          1,
	// 		Name:        "The Dud",
	// 		Description: "A blank card. Nothing happens.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleDud,
	// 	},
	// 	{
	// 		ID:          2,
	// 		Name:        "The Penny",
	// 		Description: "You found a penny on the ground. It's worth something, right?",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handlePenny,
	// 	},
	// 	{
	// 		ID:          5,
	// 		Name:        "Papercut",
	// 		Description: "You cut your finger drawing the card. Lose 10 points.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handlePapercut,
	// 	},
	// 	{
	// 		ID:          6,
	// 		Name:        "Vending Machine",
	// 		Description: "You found loose change in the return slot. Gain 25 points.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleVendingMachine,
	// 	},
	// 	{
	// 		ID:          7,
	// 		Name:        "Unexpected NIL Fee",
	// 		Description: "Kicker threatened to enter the portal. Pay 50 points to the pool to keep them on campus.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleNilFee,
	// 	},
	// 	{
	// 		ID:          8,
	// 		Name:        "Small Rebate",
	// 		Description: "Refund the cost of buying this card.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleSmallRebate,
	// 	},
	// 	{
	// 		ID:          9,
	// 		Name:        "Tip Jar",
	// 		Description: "Force the person above you on the leaderboard to give you 10 points.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleTipJar,
	// 	},
	// 	{
	// 		ID:          10,
	// 		Name:        "Hole in Pocket",
	// 		Description: "Lose 5% of your total points to the Pool.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleHoleInPocket,
	// 	},
	// 	{
	// 		ID:          11,
	// 		Name:        "Piggy Bank",
	// 		Description: "Gain 5% of your total points from the void.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handlePiggyBank,
	// 	},
	// 	{
	// 		ID:          12,
	// 		Name:        "Participation Trophy",
	// 		Description: "Gain 1 point and a pat on the back.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleParticipationTrophy,
	// 	},
	// 	{
	// 		ID:          13,
	// 		Name:        "Timeout",
	// 		Description: "You cannot buy another card for 2 hours.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleTimeout,
	// 	},
	// 	{
	// 		ID:          24,
	// 		Name:        "Bad Investment",
	// 		Description: "Lose 50 points.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleBadInvestment,
	// 	},
	// 	{
	// 		ID:          14,
	// 		Name:        "Found Wallet",
	// 		Description: "Gain 50 points.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleFoundWallet,
	// 	},
	// 	{
	// 		ID:          15,
	// 		Name:        "Charity Case",
	// 		Description: "If you are in the bottom 50% of players, gain 75 points.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleCharityCase,
	// 	},
	// 	{
	// 		ID:          16,
	// 		Name:        "Tax Season",
	// 		Description: "If you are in the top 50% of players, lose 75 points.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleTaxSeason,
	// 	},
	// 	{
	// 		ID:             17,
	// 		Name:           "Lucky Horseshoe",
	// 		Description:    "The next card you buy costs half price.",
	// 		Rarity:         "Common",
	// 		Weight:         W_Common,
	// 		Handler:        handleLuckyHorseshoe,
	// 		AddToInventory: true,
	// 	},
	// 	{
	// 		ID:             18,
	// 		Name:           "Unlucky Cat",
	// 		Description:    "The next card you buy costs double.",
	// 		Rarity:         "Common",
	// 		Weight:         W_Common,
	// 		Handler:        handleUnluckyCat,
	// 		AddToInventory: true,
	// 	},
	// 	{
	// 		ID:          19,
	// 		Name:        "Pickpocket",
	// 		Description: "Steal 50 points from a random active user.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handlePickpocketCommon,
	// 	},
	// 	{
	// 		ID:          20,
	// 		Name:        "Dropped Loot",
	// 		Description: "Give 50 points to a random active user.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleDroppedLoot,
	// 	},
	// 	{
	// 		ID:          21,
	// 		Name:        "Scraping By",
	// 		Description: "Gain 20 points.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleScrapingBy,
	// 	},
	// 	{
	// 		ID:          22,
	// 		Name:        "Rust",
	// 		Description: "Lose 20 points.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleRust,
	// 	},
	// 	{
	// 		ID:          23,
	// 		Name:        "Minor Glitch",
	// 		Description: "Gain 1-100 points (randomized).",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleMinorGlitch,
	// 	},
	// 	{
	// 		ID:          54,
	// 		Name:        "High Five",
	// 		Description: "You and a random active user high-five. You both gain 10 points.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleHighFive,
	// 	},
	// 	{
	// 		ID:          59,
	// 		Name:        "The Rick Roll",
	// 		Description: "Never gonna give you up... never gonna give you points. Lose 5 points for getting rolled.",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handleRickRoll,
	// 	},
	// 	{
	// 		ID:          61,
	// 		Name:        "Pocket Sand",
	// 		Description: "Sha-sha! You threw sand in the dealer's eyes. You get away without paying for the card (Refund cost).",
	// 		Rarity:      "Common",
	// 		Weight:      W_Common,
	// 		Handler:     handlePocketSand,
	// 	},
	// }

	// // Add to deck
	// *deck = append(*deck, commonCards...)
}
