package cards

import "perfectOddsBot/models"

func registerCommonCards(deck *[]models.Card) {
	commonCards := []models.Card{
		{
			ID:          1,
			Code:        "DUD",
			Name:        "The Dud",
			Description: "A blank card. Nothing happens.",
			Handler:     handleDud,
		},
		{
			ID:          2,
			Code:        "PEN",
			Name:        "The Penny",
			Description: "You found a penny on the ground. It's worth something, right?",
			Handler:     handlePenny,
		},
		{
			ID:          5,
			Code:        "PAP",
			Name:        "Papercut",
			Description: "You cut your finger drawing the card. Lose 10 points.",
			Handler:     handlePapercut,
		},
		{
			ID:          6,
			Code:        "VEN",
			Name:        "Vending Machine",
			Description: "You found loose change in the return slot. Gain 25 points.",
			Handler:     handleVendingMachine,
		},
		{
			ID:          7,
			Code:        "NIL",
			Name:        "Unexpected NIL Fee",
			Description: "Kicker threatened to enter the portal. Pay 50 points to the pool to keep them on campus.",
			Handler:     handleNilFee,
		},
		{
			ID:          8,
			Code:        "SMA",
			Name:        "Small Rebate",
			Description: "Refund the cost of buying this card.",
			Handler:     handleSmallRebate,
		},
		{
			ID:          9,
			Code:        "TIP",
			Name:        "Tip Jar",
			Description: "Force the person above you on the leaderboard to give you 10 points.",
			Handler:     handleTipJar,
		},
		{
			ID:          10,
			Code:        "HIP",
			Name:        "Hole in Pocket",
			Description: "Lose 5% of your total points to the Pool.",
			Handler:     handleHoleInPocket,
		},
		{
			ID:          11,
			Code:        "PIG",
			Name:        "Piggy Bank",
			Description: "Gain 5% of your total points from the void.",
			Handler:     handlePiggyBank,
		},
		{
			ID:          12,
			Code:        "PAR",
			Name:        "Participation Trophy",
			Description: "Gain 1 point and a pat on the back.",
			Handler:     handleParticipationTrophy,
		},
		{
			ID:          13,
			Code:        "TOU",
			Name:        "Timeout",
			Description: "You cannot buy another card for 2 hours.",
			Handler:     handleTimeout,
		},
		{
			ID:          24,
			Code:        "BAD",
			Name:        "Bad Investment",
			Description: "Lose 50 points.",
			Handler:     handleBadInvestment,
		},
		{
			ID:          14,
			Code:        "WAL",
			Name:        "Found Wallet",
			Description: "Gain 50 points.",
			Handler:     handleFoundWallet,
		},
		{
			ID:          15,
			Code:        "CHA",
			Name:        "Charity Case",
			Description: "If you are in the bottom 50% of players, gain 75 points.",
			Handler:     handleCharityCase,
		},
		{
			ID:          16,
			Code:        "TAX",
			Name:        "Tax Season",
			Description: "If you are in the top 50% of players, lose 75 points.",
			Handler:     handleTaxSeason,
		},
		{
			ID:             17,
			Code:           "LHS",
			Name:           "Lucky Horseshoe",
			Description:    "The next card you buy costs half price.",
			Handler:        handleLuckyHorseshoe,
			AddToInventory: true,
			IsPositive:     true,
		},
		{
			ID:             18,
			Code:           "CAT",
			Name:           "Unlucky Cat",
			Description:    "The next card you buy costs double.",
			Handler:        handleUnluckyCat,
			AddToInventory: true,
		},
		{
			ID:          19,
			Code:        "PCK",
			Name:        "Pickpocket",
			Description: "Steal 50 points from a random active user.",
			Handler:     handlePickpocketCommon,
		},
		{
			ID:          20,
			Code:        "DRO",
			Name:        "Dropped Loot",
			Description: "Give 50 points to a random active user.",
			Handler:     handleDroppedLoot,
		},
		{
			ID:          21,
			Code:        "SCR",
			Name:        "Scraping By",
			Description: "Gain 20 points.",
			Handler:     handleScrapingBy,
		},
		{
			ID:          22,
			Code:        "RUS",
			Name:        "Rust",
			Description: "Lose 20 points.",
			Handler:     handleRust,
		},
		{
			ID:          23,
			Code:        "MGL",
			Name:        "Minor Glitch",
			Description: "Gain 1-100 points (randomized).",
			Handler:     handleMinorGlitch,
		},
		{
			ID:          54,
			Code:        "HIF",
			Name:        "High Five",
			Description: "You and a random active user high-five. You both gain 10 points.",
			Handler:     handleHighFive,
		},
		{
			ID:          59,
			Code:        "ROL",
			Name:        "The Rick Roll",
			Description: "Never gonna give you up... never gonna give you points. Lose 5 points for getting rolled.",
			Handler:     handleRickRoll,
		},
		{
			ID:          61,
			Code:        "SND",
			Name:        "Pocket Sand",
			Description: "Sha-sha! You threw sand in the dealer's eyes. You get away without paying for the card (Refund cost).",
			Handler:     handlePocketSand,
		},
		{
			ID:             118,
			Code:           "KEY",
			Name:           "Spare Key",
			Description:    "Use this to ignore your next 'Timeout' or card-buying restriction.",
			Handler:        handleSpareKey,
			AddToInventory: true,
			IsPositive:     true,
		},
		{
			ID:             123,
			Code:           "COU",
			Name:           "Coupon",
			Description:    "The next card you buy is 25% off.",
			Handler:        handleCoupon,
			AddToInventory: true,
			IsPositive:     true,
		},
		{
			ID:          210,
			Code:        "POT",
			Name:        "Hot Potato",
			Description: "You lose 50 points. Pass this effect to a random user who also loses 50 points.",
			Handler:     handleHotPotato,
		},
		{
			ID:          211,
			Code:        "GOO",
			Name:        "The Gossip",
			Description: "Choose a user. Their current point balance is displayed in the server.",
			Handler:     handleTheGossip,
		},
		{
			ID:          217,
			Code:        "SK3",
			Name:        "Spy Kids 3D",
			Description: "You're now a super spy. You view the number of cards until the next Epic or Mythic card is guaranteed",
			Handler:     handleSpyKids,
		},
		{
			ID:          218,
			Code:        "TFO",
			Name:        "The Fool (🔮)",
			Description: "You take a leap of faith. Gain or lose 1-100 points at random.",
			Handler:     handleTheFool,
			Expansion:   "Tarot",
		},
	}

	*deck = append(*deck, commonCards...)
}
