package cards

import "perfectOddsBot/models"

func registerRareCards(deck *[]models.Card) {
	rareCards := []models.Card{
		{
			ID:          40,
			Code:        "UNO",
			Name:        "Uno Reverse",
			Description: "Select an active bet you placed. If it loses, you win (and vice versa).",
			Handler:     handleUnoReverse,
		},
		{
			ID:          41,
			Code:        "SOC",
			Name:        "Socialism",
			Description: "Take 90 from each of the Top 3 players and distribute it evenly among the Bottom 3 (includes you).",
			Handler:     handleSocialism,
		},
		{
			ID:          42,
			Code:        "RBH",
			Name:        "Robin Hood",
			Description: "Steal 200 points from the richest player; keep 50 for yourself, give 150 to the poorest player.",
			Handler:     handleRobinHood,
		},
		{
			ID:             44,
			Code:           "VAM",
			Name:           "The Vampire",
			Description:    "For the next 24 hours, earn 5% of every bet won by other players (up to 500 points per payout).",
			Handler:        handleVampire,
			AddToInventory: true,
			IsPositive:     true,
		},
		// {
		// 	ID:          45,
		// 	Name:        "Chaos Dunk",
		// 	Description: "Randomize the points of the middle 3 players on the leaderboard. (swaps  players' points)",
		// 	Rarity:      "Rare",
		// 	Weight:      W_Rare,
		// 	Handler:     handleChaosDunk,
		// },
		{
			ID:                   64,
			Code:                 "RSH",
			Name:                 "Red Shells",
			Description:          "The 3 people directly in front of you on the leaderboard randomly lose between 25-50 points.",
			Handler:              handleRedShells,
			RoyaltyDiscordUserID: &[]string{"447827835797766144"}[0],
		},
		{
			ID:                   67,
			Code:                 "FAC",
			Name:                 "Factory Reset",
			Description:          "If you have less than 1000 points, you are reset to 1000 points.",
			Handler:              handleFactoryReset,
			RoyaltyDiscordUserID: &[]string{"447827835797766144"}[0],
		},
		{
			ID:                   68,
			Code:                 "ANT",
			Name:                 "Anti-Anti-Bet",
			Description:          "Choose a user. You place a new bet (even odds) that that user will lose their next bet they place. (Bet will be 100 points (if possible)).",
			Handler:              handleAntiAntiBet,
			RoyaltyDiscordUserID: &[]string{"238274131722764288"}[0],
		},
		{
			ID:          31,
			Code:        "GLN",
			Name:        "Grand Larceny",
			Description: "Steal 150 points from a chosen user.",
			Handler:     handleGrandLarceny,
		},
		{
			ID:          73,
			Code:        "BHE",
			Name:        "Bank Heist",
			Description: "Steal 300 points from the pool (if possible).",
			Handler:     handleBankHeist,
		},
		{
			ID:          84,
			Code:        "EMP",
			Name:        "EMP",
			Description: "Everyone (including you and the pool) loses 5% of their points.",
			Handler:     handleEMP,
		},
		{
			ID:          85,
			Code:        "ALG",
			Name:        "Algae Bloom",
			Description: "Algae has taken over the pool! For the next 24 hours, every card drawn drains 100 points from the pool.",
			Handler:     handleAlgaeBloom,
		},
		{
			ID:          88,
			Code:        "THP",
			Name:        "The High Priestess (🔮)",
			Description: "Hidden Knowledge. Choose a user. Reveal their inventory.",
			Handler:     handleTheHighPriestess,
			Expansion:   "Tarot",
		},
		{
			ID:          89,
			Code:        "TEM",
			Name:        "The Empress (🔮)",
			Description: "Abundance for the poor. The player in last place gains 200 points.",
			Handler:     handleTheEmpress,
			Expansion:   "Tarot",
		},
		{
			ID:             90,
			Code:           "TCH",
			Name:           "The Chariot (🔮)",
			Description:    "Momentum. Your next 3 cards cost 0.",
			Handler:        handleTheChariot,
			AddToInventory: true,
			IsPositive:     true,
			Expansion:      "Tarot",
		},
		{
			ID:          91,
			Code:        "JUS",
			Name:        "Justice (🔮)",
			Description: "Choose a user. You both have your balances set to the average of your points. (max 500 points difference)",
			Handler:     handleJustice,
			Expansion:   "Tarot",
		},
		{
			ID:             92,
			Code:           "HMA",
			Name:           "The Hanged Man (🔮)",
			Description:    "Lose 150 points immediately. In 24 hours gain 400 points from the pool.",
			Handler:        handleTheHangedMan,
			AddToInventory: true,
			Expansion:      "Tarot",
		},
		{
			ID:          93,
			Code:        "STA",
			Name:        "The Star (🔮)",
			Description: "Hope in the darkness. If you are in the bottom 25% of the leaderboard, you gain 300 points.",
			Handler:     handleTheStar,
			Expansion:   "Tarot",
		},
		{
			ID:             94,
			Code:           "MOO",
			Name:           "The Moon (🔮)",
			Description:    "Illusion. The next negative effect played against you, targets a random user instead.",
			Handler:        handleTheMoon,
			AddToInventory: true,
			IsPositive:     true,
			Expansion:      "Tarot",
		},
		{
			ID:          30001,
			Code:        "UND",
			Name:        "The Underdog (🏟️)",
			Description: "If you are in the bottom 25% of players, gain 250 points from the Pool. Otherwise gain 50 points.",
			Handler:     handleUnderdog,
			Expansion:   "Collegiate",
		},
		{
			ID:             30002,
			Name:           "Full Ride (🏟️)",
			Code:           "FRD",
			Description:    "Your next card purchase is free.",
			Handler:        handleFullRide,
			AddToInventory: true,
			Expansion:      "Collegiate",
			IsPositive:     true,
		},
		{
			ID:          30003,
			Code:        "HCAM",
			Name:        "Heisman Campaign (🏟️)",
			Description: "If you are in the top 5 players, gain 300 points and your next bet payout is reduced by 15%. Otherwise gain 100 points.",
			Handler:     handleHeismanCampaign,
			Expansion:   "Collegiate",
		},
	}

	*deck = append(*deck, rareCards...)
}
