package cards

import (
	"perfectOddsBot/models"
)

func registerUncommonCards(deck *[]models.Card) {
	uncommonCards := []models.Card{
		{
			ID:          4,
			Code:        "PET",
			Name:        "Petty Theft",
			Description: "Choose a user. Steal 50 of their points.",
			Handler:     handlePettyTheft,
		},
		{
			ID:             25,
			Code:           "SHI",
			Name:           "The Shield",
			Description:    "Blocks the next 'Steal' or negative effect played against you.",
			Handler:        handleShield,
			AddToInventory: true,
		},
		{
			ID:                   26,
			Code:                 "MGL",
			Name:                 "Major Glitch",
			Description:          "Everyone in the server gets 100 points.",
			Handler:              handleMajorGlitch,
			RoyaltyDiscordUserID: &[]string{"195444122578845696"}[0],
		},
		{
			ID:             28,
			Code:           "GDO",
			Name:           "Generous Donation",
			Description:    "You pay for the next (standard cost) card bought by another user.",
			Handler:        handleGenerousDonation,
			AddToInventory: true,
		},
		{
			ID:          29,
			Code:        "JES",
			Name:        "The Jester",
			Description: "Choose a user. Mute them for 15 minutes.",
			Handler:     handleJester,
		},
		{
			ID:          30,
			Code:        "STI",
			Name:        "Stimulus Check",
			Description: "Everyone in the server gets 50 points.",
			Handler:     handleStimulusCheck,
		},
		// // {
		// // 	ID:          32,
		// // 	Name:        "Identity Theft",
		// // 	Description: "Swap nicknames with another user for 24 hours.",
		// // 	Rarity:      "Uncommon",
		// // 	Weight:      W_Uncommon,
		// // 	Handler:     handleIdentityTheft,
		// // },
		{
			ID:          34,
			Code:        "BFZ",
			Name:        "Bet Freeze",
			Description: "Choose a user. Prevent them from placing bets for 2 hours.",
			Handler:     handleBetFreeze,
		},
		{
			ID:             35,
			Code:           "BIS",
			Name:           "Bet Insurance",
			Description:    "If you lose your next bet, get 25% of your wager back.",
			Handler:        handleBetInsurance,
			AddToInventory: true,
		},
		{
			ID:          36,
			Code:        "QFL",
			Name:        "Quick Flip",
			Description: "Flip a coin. Heads: Double your card cost back. Tails: Get nothing.",
			Handler:     handleQuickFlip,
		},
		{
			ID:                   63,
			Code:                 "GSH",
			Name:                 "Green Shells",
			Description:          "3 people are randomly selected to randomly lose between 1-25 points.",
			Handler:              handleGreenShells,
			RoyaltyDiscordUserID: &[]string{"447827835797766144"}[0],
		},
		{
			ID:                   65,
			Code:                 "WAM",
			Name:                 "Whack-a-Mole",
			Description:          "Bonk 3-5 random players who each randomly lose between 1-10 points",
			Handler:              handleWhackAMole,
			RoyaltyDiscordUserID: &[]string{"447827835797766144"}[0],
		},
		{
			ID:             37,
			Code:           "LSK",
			Name:           "Loan Shark",
			Description:    "Get 500 points now, but you automatically lose 600 points in 3 days.",
			Handler:        handleLoanShark,
			AddToInventory: true,
		},
		{
			ID:          75,
			Code:        "ITR",
			Name:        "Insider Trading",
			Description: "Steal 100 points from the pool.",
			Handler:     handleInsiderTrading,
		},
		{
			ID:          125,
			Code:        "CWD",
			Name:        "Crowdfund",
			Description: "You get 1 point for every user in the server.",
			Handler:     handleCrowdfund,
		},
		// {
		// 	ID:          201,
		// 	Name:        "The Magnet",
		// 	Description: "Steal 30 points from the users directly above and below you on the leaderboard.",
		// 	Rarity:      "Uncommon",
		// 	Weight:      W_Uncommon,
		// 	Handler:     handleMagnet,
		// },
		{
			ID:          202,
			Code:        "RPK",
			Name:        "Reverse Pickpocket",
			Description: "Sneakily give 150 points to a random user.",
			Handler:     handleReversePickpocket,
		},
		{
			ID:             208,
			Code:           "SPS",
			Name:           "Shopping Spree",
			Description:    "Reduces all your card-buying costs by 50% for 12 hours.",
			Handler:        handleShoppingSpree,
			AddToInventory: true,
		},
		// // {
		// // 	ID:          209,
		// // 	Name:        "The Merchant",
		// // 	Description: "Trade 75 points to immediately receive a random Common card.",
		// // 	Rarity:      "Uncommon",
		// // 	Weight:      W_Uncommon,
		// // 	Handler:     handleMerchant,
		// // },
		// {
		// 	ID:          213,
		// 	Name:        "Tax Collector",
		// 	Description: "The players in 1st, 2nd, and 3rd place each pay you 25 points.",
		// 	Rarity:      "Uncommon",
		// 	Weight:      W_Uncommon,
		// 	Handler:     handleTaxCollector,
		// },
		{
			ID:          214,
			Code:        "BHN",
			Name:        "Bounty Hunter",
			Description: "Choose a user. They next person to steal points from them gains an extra 100 points from the pool.",
			Handler:     handleBountyHunter,
		},
		{
			ID:          215,
			Code:        "SDS",
			Name:        "Social Distancing",
			Description: "Choose a user. They gain a shield, but they also cannot buy any new cards for 2 hours.",
			Handler:     handleSocialDistancing,
		},
		{
			ID:          216,
			Code:        "DUE",
			Name:        "DUEL!",
			Description: "Choose a user. You both roll a die. The highest roll wins 100 points from the loser. If you tie, you both lose 50 points.",
			Handler:     handleDuel,
		},
		{
			ID:          212,
			Code:        "TAG",
			Name:        "Tag!",
			Description: "Choose a user. For the next 12 hours, they gain 1 point every time anyone buys a card.",
			Handler:     handleTag,
		},
		{
			ID:          72,
			Code:        "GAM",
			Name:        "The Gambler",
			Description: "**CHOICE CARD** You choose one of the following options:",
			Options: []models.CardOption{
				{
					ID:          1,
					Name:        "Yes",
					Description: "50/50 chance to win 2x your next bet that gets resolved, or double your loss.",
				},
				{
					ID:          2,
					Name:        "No",
					Description: "Nothing happens.",
				},
			},
			Handler:              handleGambler,
			RoyaltyDiscordUserID: &[]string{"447827835797766144"}[0],
			AddToInventory:       true,
		},
	}

	*deck = append(*deck, uncommonCards...)
}
