package cards

import (
	"perfectOddsBot/models"
)

func registerUncommonCards(deck *[]models.Card) {
	uncommonCards := []models.Card{
		{
			ID:          4,
			Name:        "Petty Theft",
			Description: "Choose a user. Steal 50 of their points.",
			Rarity:      "Uncommon",
			Weight:      W_Uncommon,
			Handler:     handlePettyTheft,
		},
		{
			ID:             25,
			Name:           "The Shield",
			Description:    "Blocks the next 'Steal' or negative effect played against you.",
			Rarity:         "Uncommon",
			Weight:         W_Uncommon,
			Handler:        handleShield,
			AddToInventory: true,
		},
		{
			ID:                   26,
			Name:                 "Major Glitch",
			Description:          "Everyone in the server gets 100 points.",
			Rarity:               "Uncommon",
			Weight:               W_Uncommon,
			Handler:              handleMajorGlitch,
			RoyaltyDiscordUserID: &[]string{"195444122578845696"}[0],
		},
		{
			ID:                   27,
			Name:                 "Double Down",
			Description:          "The payout of your next winning bet is increased by 2x",
			Rarity:               "Uncommon",
			Weight:               W_Uncommon,
			Handler:              handleDoubleDown,
			AddToInventory:       true,
			RoyaltyDiscordUserID: &[]string{"130863485969104896"}[0],
		},
		{
			ID:             28,
			Name:           "Generous Donation",
			Description:    "You pay for the next (standard cost) card bought by another user.",
			Rarity:         "Uncommon",
			Weight:         W_Uncommon,
			Handler:        handleGenerousDonation,
			AddToInventory: true,
		},
		{
			ID:          29,
			Name:        "The Jester",
			Description: "Choose a user. Mute them for 15 minutes.",
			Rarity:      "Uncommon",
			Weight:      W_Uncommon,
			Handler:     handleJester,
		},
		{
			ID:          30,
			Name:        "Stimulus Check",
			Description: "Everyone in the server gets 50 points.",
			Rarity:      "Uncommon",
			Weight:      W_Uncommon,
			Handler:     handleStimulusCheck,
		},
		// // {
		// // 	ID:          32,
		// // 	Name:        "Identity Theft",
		// // 	Description: "Swap nicknames with another user for 24 hours.",
		// // 	Rarity:      "Uncommon",
		// // 	Weight:      W_Uncommon,
		// // 	Handler:     handleIdentityTheft,
		// // },
		{
			ID:          34,
			Name:        "Bet Freeze",
			Description: "Choose a user. Prevent them from placing bets for 2 hours.",
			Rarity:      "Uncommon",
			Weight:      W_Uncommon,
			Handler:     handleBetFreeze,
		},
		{
			ID:             35,
			Name:           "Bet Insurance",
			Description:    "If you lose your next bet, get 25% of your wager back.",
			Rarity:         "Uncommon",
			Weight:         W_Uncommon,
			Handler:        handleBetInsurance,
			AddToInventory: true,
		},
		{
			ID:          36,
			Name:        "Quick Flip",
			Description: "Flip a coin. Heads: Double your card cost back. Tails: Get nothing.",
			Rarity:      "Uncommon",
			Weight:      W_Uncommon,
			Handler:     handleQuickFlip,
		},
		{
			ID:                   63,
			Name:                 "Green Shells",
			Description:          "3 people are randomly selected to randomly lose between 1-25 points.",
			Rarity:               "Uncommon",
			Weight:               W_Uncommon,
			Handler:              handleGreenShells,
			RoyaltyDiscordUserID: &[]string{"447827835797766144"}[0],
		},
		{
			ID:                   65,
			Name:                 "Whack-a-Mole",
			Description:          "Bonk 3-5 random players who each randomly lose between 1-10 points",
			Rarity:               "Uncommon",
			Weight:               W_Uncommon,
			Handler:              handleWhackAMole,
			RoyaltyDiscordUserID: &[]string{"447827835797766144"}[0],
		},
		{
			ID:             37,
			Name:           "Loan Shark",
			Description:    "Get 500 points now, but you automatically lose 600 points in 3 days.",
			Rarity:         "Uncommon",
			Weight:         W_Uncommon,
			Handler:        handleLoanShark,
			AddToInventory: true,
		},
		{
			ID:          75,
			Name:        "Insider Trading",
			Description: "Steal 100 points from the pool.",
			Rarity:      "Uncommon",
			Weight:      W_Uncommon,
			Handler:     handleInsiderTrading,
		},
		{
			ID:          125,
			Name:        "Crowdfund",
			Description: "You get 1 point for every user in the server.",
			Rarity:      "Uncommon",
			Weight:      W_Uncommon,
			Handler:     handleCrowdfund,
		},
		// {
		// 	ID:          201,
		// 	Name:        "The Magnet",
		// 	Description: "Steal 30 points from the users directly above and below you on the leaderboard.",
		// 	Rarity:      "Uncommon",
		// 	Weight:      W_Uncommon,
		// 	Handler:     handleMagnet,
		// },
		{
			ID:          202,
			Name:        "Reverse Pickpocket",
			Description: "Sneakily give 150 points to a random user.",
			Rarity:      "Uncommon",
			Weight:      W_Uncommon,
			Handler:     handleReversePickpocket,
		},
		{
			ID:             208,
			Name:           "Shopping Spree",
			Description:    "Reduces all your card-buying costs by 50% for 12 hours.",
			Rarity:         "Uncommon",
			Weight:         W_Uncommon,
			Handler:        handleShoppingSpree,
			AddToInventory: true,
		},
		// // {
		// // 	ID:          209,
		// // 	Name:        "The Merchant",
		// // 	Description: "Trade 75 points to immediately receive a random Common card.",
		// // 	Rarity:      "Uncommon",
		// // 	Weight:      W_Uncommon,
		// // 	Handler:     handleMerchant,
		// // },
		// {
		// 	ID:          213,
		// 	Name:        "Tax Collector",
		// 	Description: "The players in 1st, 2nd, and 3rd place each pay you 25 points.",
		// 	Rarity:      "Uncommon",
		// 	Weight:      W_Uncommon,
		// 	Handler:     handleTaxCollector,
		// },
		{
			ID:          214,
			Name:        "Bounty Hunter",
			Description: "Choose a user. They next person to steal points from them gains an extra 100 points from the pool.",
			Rarity:      "Uncommon",
			Weight:      W_Uncommon,
			Handler:     handleBountyHunter,
		},
		{
			ID:          215,
			Name:        "Social Distancing",
			Description: "Choose a user. They gain a shield, but they also cannot buy any new cards for 2 hours.",
			Rarity:      "Uncommon",
			Weight:      W_Uncommon,
			Handler:     handleSocialDistancing,
		},
		{
			ID:          216,
			Name:        "DUEL!",
			Description: "Choose a user. You both roll a die. The highest roll wins 100 points from the loser. If you tie, you both lose 50 points.",
			Rarity:      "Uncommon",
			Weight:      W_Uncommon,
			Handler:     handleDuel,
		},
		{
			ID:          212,
			Name:        "Tag!",
			Description: "Choose a user. For the next 12 hours, they gain 1 point every time anyone buys a card.",
			Rarity:      "Rare",
			Weight:      W_Rare,
			Handler:     handleTag,
		},
	}

	*deck = append(*deck, uncommonCards...)
}
